final mockWatchlistResponse = {
  "groups": [
    {
      "groupName": "watchlist 1",
      "symbols": [
        {
          "name": "NATIONALUM",
          "exchange": "NSE",
          "buyQty": 82,
          "buyPrice": 193.71,
          "sellQty": 30,
          "sellPrice": 193.74,
          "lastTradedPrice": 193.70,
          "change": 4.02,
          "changePercent": 2.11,
        },
        {
          "name": "WIPRO",
          "exchange": "NSE",
          "buyQty": 164,
          "buyPrice": 310.15,
          "sellQty": 954,
          "sellPrice": 310.20,
          "lastTradedPrice": 310.15,
          "change": -0.05,
          "changePercent": -0.01,
        },
        {
          "name": "UPL",
          "exchange": "NSE",
          "buyQty": 81,
          "buyPrice": 638.00,
          "sellQty": 87,
          "sellPrice": 638.10,
          "lastTradedPrice": 637.95,
          "change": 17.45,
          "changePercent": 2.81,
        },
        {
          "name": "ULTRACEMCO",
          "exchange": "NSE",
          "buyQty": 3,
          "buyPrice": 11621.20,
          "sellQty": 9,
          "sellPrice": 11625.00,
          "lastTradedPrice": 11621.50,
          "change": 143.00,
          "changePercent": 1.24,
        },
        {
          "name": "TITAN",
          "exchange": "NSE",
          "buyQty": 84,
          "buyPrice": 3264.05,
          "sellQty": 34,
          "sellPrice": 3264.40,
          "lastTradedPrice": 3264.05,
          "change": 8.60,
          "changePercent": 0.26,
        },
        {
          "name": "TECHM",
          "exchange": "NSE",
          "buyQty": 24,
          "buyPrice": 1686.50,
          "sellQty": 50,
          "sellPrice": 1686.65,
          "lastTradedPrice": 1686.60,
          "change": 6.40,
          "changePercent": 0.38,
        },
        {
          "name": "TCS",
          "exchange": "NSE",
          "buyQty": 12,
          "buyPrice": 3942.00,
          "sellQty": 13,
          "sellPrice": 3942.70,
          "lastTradedPrice": 3942.00,
          "change": -8.15,
          "changePercent": -0.20,
          "is52WeekLow": true,
        },
      ],
    },
    {"groupName": "Watchlist 🤖", "symbols": []},
    {"groupName": "Watchlist 3", "symbols": []},
    {"groupName": "NIFTY", "symbols": []},
  ],
};
